# sources.nix — auto-generated by CI.  URLs point at this repo's own GitHub releases.
{
  koreader = {
    version = "v2026.07.1";
    arm64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-v2026.07.1/koreader-macos-arm64.7z";
      sha256 = "sha256-9vP+2mulGeKq0WmS5KqlfGFd56if+Bb4JOFaS95uyxM=";
    };
    x86_64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-v2026.07.1/koreader-macos-x86_64.7z";
      sha256 = "sha256-2Uxvq3p8Ev2Ku4lZbfKD+7zsmFGJI8aUsUDDZgHHYU4=";
    };
  };
  koreader-nightly = {
    arm64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-nightly/koreader-macos-arm64.7z";
      sha256 = "sha256-w8CL9aNm4cgkUnS6+rw7O8zpM6QhevQBzTco1jK8qwc=";
    };
    x86_64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-nightly/koreader-macos-x86_64.7z";
      sha256 = "sha256-l9OIDGAAYY92YzCdtatYRdjIuTxGXf3ekC9+kUZnbnQ=";
    };
  };
}
