# sources.nix — auto-generated by CI.  URLs point at this repo's own GitHub releases.
{
  koreader = {
    version = "v2026.07.1";
    arm64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-v2026.07.1/koreader-macos-arm64.7z";
      sha256 = "sha256-9vP+2mulGeKq0WmS5KqlfGFd56if+Bb4JOFaS95uyxM=";
    };
    x86_64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-v2026.07.1/koreader-macos-x86_64.7z";
      sha256 = "sha256-2Uxvq3p8Ev2Ku4lZbfKD+7zsmFGJI8aUsUDDZgHHYU4=";
    };
  };
  koreader-nightly = {
    arm64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-nightly/koreader-macos-arm64.7z";
      sha256 = "sha256-L5HVGGNRTZCxPqrNOhKuBdxj9xBavD3soL2jg8sOQXI=";
    };
    x86_64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-nightly/koreader-macos-x86_64.7z";
      sha256 = "sha256-FhslN4pNMz2HN1G+5d4sxT/Qs012+UxlEenF3CQ0PmQ=";
    };
  };
}
